In [1]:
import random
import time
import numpy as np

In [2]:
a = []
for i in range(100000000):
    a.append(random.random())
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(f"time1 = {t2 - t1}, time2 = {t5 - t4}")

time1 = 3.5956060886383057, time2 = 0.14011693000793457


In [4]:
list1 = [1, 2, 3, 4]
one_array = np.array(list1)
print(type(list1))
print(list1)
print('*' * 30)
print(type(one_array))
print(one_array)

<class 'list'>
[1, 2, 3, 4]
******************************
<class 'numpy.ndarray'>
[1 2 3 4]


In [5]:
t1 = np.array([1, 2, 3])
print(type(t1))
print(t1)

<class 'numpy.ndarray'>
[1 2 3]


In [6]:
t2 = np.array(range(10))
print(type(t2))
print(t2)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [8]:
t3 = np.arange(0, 10, 2)
print(type(t3))
print(t3)

<class 'numpy.ndarray'>
[0 2 4 6 8]


创建2维列表

In [9]:
list2 = [[1, 2], [3, 4], [5, 6]]
two_array = np.array(list2)
print(type(two_array))
print(two_array)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]


In [11]:
print(two_array.ndim)  # 数组的维度
print(two_array.shape)  #数组的形状
print(two_array.size)  # 数组总共有多少个元素

2
(3, 2)
6


In [13]:
four = np.array([[1, 2, 3], [4, 5, 6]])
print(four.shape)
print(four)
print('*' * 30)
four = four.reshape(3, 2)
print(four.shape)
print(four)

(2, 3)
[[1 2 3]
 [4 5 6]]
******************************
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [15]:
five = four.reshape((6,), order='C')  # 默认情况'C'以行为主顺序展开，'F'表示以列为主的顺序展开
print(five)

[1 2 3 4 5 6]


In [16]:
t = np.arange(24)
print(t)
print(t.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [19]:
t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [21]:
a = np.array([9, 12, 88, 14, 25])
list_a = a.tolist()
print(list_a)
print(type(list_a))

[9, 12, 88, 14, 25]
<class 'list'>


In [22]:
f = np.array([1, 2, 3, 4, 5], dtype=np.int16)
print(f.itemsize)  # np.int8是一个字节,所以是两个字节

2


In [25]:
print(f.dtype)  # 数据类型
print(f.shape)  # 数组形状
print(f.ndim)  # 数组维度

int16
(5,)
1


In [27]:
f1 = f.astype(np.int64)  # 调整数据类型
print(f1.dtype)

int64


In [28]:
print(round(random.random(), 2))  # 随机生成数，取两位小数

0.47


In [29]:
arr = np.array([random.random() for i in range(10)])  # 随机生成numpy数组，并取两位小数
print(np.round(arr, 2))

[0.02 0.47 0.68 0.43 0.75 0.23 0.11 0.24 0.91 0.77]
